
import
  os, options, unittest, "../../../runtime/nim/kaitai"
import ../../compiled/nim/default_big_endian


proc `==`[T: SomeInteger](x: seq[T]; y: seq[int]): bool =
  result = true
  for i in 0 ..< x.len:
    if int(x[i]) != y[i]:
      return false

proc `==`[T](x: Option[T]; y: T): bool =
  get(x) == y
# Autogenerated from KST: please remove this line if doing any edits by hand!

let r = DefaultBigEndian.fromFile("src" / "enum_0.bin")

check(r.one == 117440512)
